import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@chartloapp/ui/src/index.css';
import { Toaster } from 'react-hot-toast';
import { ThemeProvider } from '@chartloapp/ui';
import { StoreProvider } from '@chartloapp/state';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className="container container-2xl mx-auto">
              <Toaster />
              {children}
            </main>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
